
export const LIST_CONTACTS = 'LIST_CONTACTS';
export const SET_CURRENT_CONTACT = 'SET_CURRENT_CONTACT';
export const SET_LOADING = 'SET_LOADING';
export const ADD_CONTACT = 'ADD_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';